// ============================================
// PROJETS — Basés sur le CV d'Aurélien
// Modifiez ce fichier pour ajouter vos projets !
// ============================================
const projects = [
  {
    id: 1,
    title: "🏢 Infrastructure NextHope",
    description: "Administration et supervision d'infrastructures réseau, systèmes et sécurité. Gestion cloud, téléphonie IP et rédaction de documentation technique.",
    image: null,
    technologies: ["Cisco", "FortiGate", "VMware", "Linux", "VoIP"],
    category: "reseaux",
    liveUrl: "#",
    githubUrl: "#",
    featured: true,
  },
  {
    id: 2,
    title: "☁️ Cloud OpenStack — ESPA",
    description: "Conception et mise en place d'une infrastructure cloud complète basée sur OpenStack : Nova, Neutron, Glance, Horizon, Keystone. Automatisation du déploiement.",
    image: null,
    technologies: ["OpenStack", "Linux", "Virtualisation", "Neutron"],
    category: "cloud",
    liveUrl: "#",
    githubUrl: "#",
    featured: true,
  },
  {
    id: 3,
    title: "🔒 Sécurité & Pare-feux",
    description: "Configuration de politiques de sécurité avancées sur FortiGate, Cisco ASA/Firepower, pfSense. Déploiement IDS/IPS Snort et portail captif.",
    image: null,
    technologies: ["FortiGate", "Cisco ASA", "pfSense", "Snort IDS"],
    category: "securite",
    liveUrl: "#",
    githubUrl: "#",
    featured: true,
  },
  {
    id: 4,
    title: "📞 Téléphonie VoIP — Ministère",
    description: "Mise en place d'un système VoIP interne complet : trunks SIP, dial-peers, codecs optimisés, routage d'appels et messagerie instantanée inter-services.",
    image: null,
    technologies: ["Cisco CME", "Asterisk", "SIP", "Yeastar"],
    category: "voip",
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    id: 5,
    title: "📡 Réseau WiMAX — CIR DIANA",
    description: "Configuration et optimisation de réseaux WiMAX, déploiement Ubiquiti, études de liaison radio (zone de Fresnel) et conception du réseau intranet.",
    image: null,
    technologies: ["WiMAX", "Ubiquiti", "Radio", "LAN/WAN"],
    category: "reseaux",
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    id: 6,
    title: "🌐 App Web État Civil",
    description: "Développement d'une application web de remontée des statistiques d'état civil pour le Ministère de l'Intérieur. Support utilisateur et documentation.",
    image: null,
    technologies: ["PHP", "HTML", "CSS", "MySQL"],
    category: "dev",
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    id: 7,
    title: "📹 Vidéosurveillance IP",
    description: "Installation et configuration de systèmes de vidéosurveillance IP : caméras Hikvision, NVR, accès distant web/mobile, stockage et alertes.",
    image: null,
    technologies: ["Hikvision", "NVR", "IP Camera", "Réseau"],
    category: "securite",
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    id: 8,
    title: "🖥️ Virtualisation Multi-Plateformes",
    description: "Déploiement de VM sur VMware vSphere/ESXi et Proxmox VE. Gestion centralisée via vCenter, conteneurs et environnements de test.",
    image: null,
    technologies: ["VMware", "Proxmox", "ESXi", "vCenter"],
    category: "cloud",
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
];

const categories = [
  { key: "all", label: "🔥 Tous" },
  { key: "reseaux", label: "🌐 Réseaux" },
  { key: "cloud", label: "☁️ Cloud" },
  { key: "securite", label: "🔒 Sécurité" },
  { key: "voip", label: "📞 VoIP" },
  { key: "dev", label: "💻 Dev" },
];
